production:
  primary: &primary_production
    <<: *default
    adapter: postgresql
    encoding: unicode
    pool: 5
    database: mysite
    username: mysite
    password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
    url: <%= ENV['DATABASE_URL'] %>