default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mysite_development

test:
  <<: *default
  database: mysite_test

production:
  primary: &primary_production
    <<: *default
    database: mysite
    username: mysite
    password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
    url: <%= ENV['DATABASE_URL'] %>

  # 追加：solid_cable 用の設定（メインDBと同じ接続を使用）
  cable:
    <<: *primary_production

  # 追加：solid_queue や solid_cache もエラーにならないよう追加
  cache:
    <<: *primary_production
  queue:
    <<: *primary_production